name: contacts_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/nurcinta.jpg
    - assets/images/arfah.jpg
    - assets/images/ayu.jpg

flutter_native_splash:
  color: "#0000ff" 
  image: assets/images/Logo.png
  android: true
